Repository AY2223S2-CS2103T-W13-2/tp, pull requests merged in 2023-03, with the labels that each got.

#17 Update dg v1.1
  docs/DeveloperGuide.md
Labels: documentation

#18 Update name of project from Unibook to SportSync in User Guide.
  README.md
  docs/UserGuide.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
  docs/images/Ui.png
  docs/index.md
  docs/team/tempura-person.md
Labels: documentation

#20 Updated AboutUs doc
  docs/AboutUs.md
  docs/images/Oliverloo0909.png
  docs/images/Tempura-Person.png
  docs/images/jengoc415.png
  docs/images/tricixg.png
Labels: documentation

#21 Created tricixg.md
  docs/team/tricixg.md
Labels: documentation

#22 Update AboutUs naming convention
  docs/AboutUs.md
  docs/images/oliverloo0909.png
  docs/images/tempura-person.png
Labels: documentation

#29 Add sort command.
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/tempura-person.md
  docs/team/tricixg.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: enhancement, type.Story

#34 Implement fuzzy search in NameContainsKeywordsPredicate
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: enhancement, type.Story

#33 Branch grouping function
  src/main/java/seedu/address/logic/commands/DisplayGroupCommand.java
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/logic/parser/ShowCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/TagContainsGroupsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/model/tag/exceptions/DuplicateTagException.java
  src/main/java/seedu/address/model/tag/exceptions/TagNotFoundException.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DisplayGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/GroupCommandTest.java
  src/test/java/seedu/address/logic/commands/ShowCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/GroupCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ShowCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/model/tag/UniqueTagListTest.java
Labels: type.Story

#40 Session Property
  build.gradle
  docs/tutorials/RemovingFields.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Session.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/SessionTest.java
  src/test/java/seedu/address/model/tag/UniqueTagListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement, type.Story

#46 Update User Guide, Developer Guide and name of .jar file.
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/tempura-person.md
Labels: documentation

#47 Change colour scheme and logo of SportSync.
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/GroupAddCommand.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/sportsync_logo.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/logic/commands/GroupAddCommandTest.java
Labels: enhancement

#50 Implement Undo & Redo commands.
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/tempura-person.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GroupAddCommand.java
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/VersionedAddressBookTest.java
Labels: documentation, enhancement, type.Story

#51 Calendar interface
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/CalendarLogic.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/calendar/CalendarEvent.java
  src/main/java/seedu/address/model/calendar/CalendarMonth.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Session.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/calendar/CalendarButton.java
  src/main/java/seedu/address/ui/calendar/CalendarDisplay.java
  src/main/java/seedu/address/ui/calendar/CalendarEventListPanel.java
  src/main/java/seedu/address/ui/calendar/CalendarGrid.java
  src/main/java/seedu/address/ui/calendar/CalendarPopup.java
  src/main/java/seedu/address/ui/calendar/CalendarPopupContent.java
  src/main/java/seedu/address/ui/calendar/EventButton.java
  src/main/java/seedu/address/ui/calendar/NextButton.java
  src/main/java/seedu/address/ui/calendar/PreviousButton.java
  src/main/java/seedu/address/ui/calendar/TopCalendar.java
  src/main/resources/images/23Date.png
  src/main/resources/images/23address.png
  src/main/resources/images/23timer.png
  src/main/resources/images/address.png
  src/main/resources/images/clock.png
  src/main/resources/view/CalendarDisplay.fxml
  src/main/resources/view/CalendarEventListPanel.fxml
  src/main/resources/view/CalendarGrid.fxml
  src/main/resources/view/CalendarPopup.fxml
  src/main/resources/view/CalendarPopupContent.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EventButton.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NextButton.fxml
  src/main/resources/view/PreviousButton.fxml
  src/main/resources/view/TopCalendar.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/calendar/CalendarEventTest.java
  src/test/java/seedu/address/model/calendar/CalendarMonthTest.java
  src/test/java/seedu/address/model/person/SessionTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/CalendarEventBuilder.java
  src/test/java/seedu/address/testutil/TypicalCalendarEvents.java
Labels: enhancement, type.Story

#52 Added Documentation for the DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/GroupingFunctionality/GroupListclassdiagram.puml
  docs/diagrams/GroupingFunctionality/GroupObject.puml
  docs/diagrams/GroupingFunctionality/GroupRemoveSequenceDiagram.puml
  docs/diagrams/GroupingFunctionality/sequence_group.puml
  docs/diagrams/GroupingFunctionality/style-group.puml
  docs/diagrams/ModelClassDiagram3.puml
  docs/images/GroupListclassdiagram.png
  docs/images/GroupObject.png
  docs/images/UniqueGroupListClass.png
  docs/team/oliverloo0909.md
  docs/tutorials/RemovingFields.md
Labels: documentation

#53 Enhanced sort feature to sort by specified attribute
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: enhancement

#54 Add hasPaid and isPresent attributes
  src/main/java/seedu/address/model/person/HasPaid.java
  src/main/java/seedu/address/model/person/IsPresent.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/person/HasPaidTest.java
  src/test/java/seedu/address/model/person/IsPresentTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: enhancement

#55 Fix JavaFX bug
  build.gradle
  src/main/resources/view/CalendarDisplay.fxml
  src/main/resources/view/CalendarEventListPanel.fxml
  src/main/resources/view/CalendarGrid.fxml
  src/main/resources/view/CalendarPopup.fxml
  src/main/resources/view/CalendarPopupContent.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/EventButton.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NextButton.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/PreviousButton.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/main/resources/view/TopCalendar.fxml
Labels: bug

#64 Remove Session from Person
  docs/tutorials/RemovingFields.md
  src/main/java/seedu/address/logic/CalendarLogic.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GroupAddCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/calendar/CalendarEvent.java
  src/main/java/seedu/address/model/calendar/CalendarMonth.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/calendar/CalendarDisplay.java
  src/main/java/seedu/address/ui/calendar/CalendarEventListPanel.java
  src/main/java/seedu/address/ui/calendar/CalendarPopup.java
  src/main/java/seedu/address/ui/calendar/CalendarPopupContent.java
  src/main/java/seedu/address/ui/calendar/EventButton.java
  src/main/java/seedu/address/ui/calendar/NextButton.java
  src/main/java/seedu/address/ui/calendar/PreviousButton.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/GroupAddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/calendar/CalendarEventTest.java
  src/test/java/seedu/address/model/calendar/CalendarMonthTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/SessionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/CalendarEventBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalCalendarEvents.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: bug

#66 added id to Person class
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Session.java
Labels: enhancement

#70 Added mark and unmark features
  src/main/java/seedu/address/model/session/Session.java
Labels: enhancement

#71 Edited hash function and added attendees in toString
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/session/IdBooleanPair.java
  src/main/java/seedu/address/model/session/NameBooleanPair.java
  src/main/java/seedu/address/model/session/Session.java
Labels: enhancement

#72 Add student-add command and fix storage
  src/main/java/seedu/address/logic/commands/GroupAddCommand.java
  src/main/java/seedu/address/logic/commands/StudentAddCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteSessionCommandParser.java
  src/main/java/seedu/address/logic/parser/StudentAddCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/session/SessionName.java
  src/main/java/seedu/address/storage/JsonAdaptedNameBooleanPair.java
  src/main/java/seedu/address/storage/JsonAdaptedSession.java
Labels: enhancement

#84 Try catch statement for empty Session and fix calendar navigation
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SessionListPanel.java
Labels: bug

#85 Fix UI colour scheme.
  src/main/resources/view/DarkTheme.css
Labels: enhancement

#87 Added add-tag and remove-tag commands
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/DisplayGroupCommand.java
  src/main/java/seedu/address/logic/commands/GroupAddCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
  src/test/java/seedu/address/logic/commands/DisplayGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/GroupAddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: enhancement

#86 implemented total cost and attendance details in sessions
  src/main/java/seedu/address/logic/commands/StudentAddCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/PayRate.java
  src/main/java/seedu/address/model/session/Session.java
Labels: bug, enhancement

#90 Reformatted name to ignore case in all methods
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/StudentAddCommand.java
  src/main/java/seedu/address/logic/commands/StudentRemoveCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/session/SessionName.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: bug

#89 Reformatted hashMap intialisation
  src/main/java/seedu/address/model/session/Session.java
Labels: enhancement

#91 Modify Name Constructor
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/session/SessionName.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: documentation, enhancement

#92 Added editSession command
  src/main/java/seedu/address/logic/commands/CreateSessionCommand.java
  src/main/java/seedu/address/logic/commands/EditSessionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditSessionCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/calendar/CalendarEvent.java
  src/main/java/seedu/address/model/session/NamePayRatePair.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/storage/JsonAdaptedNamePayRatePair.java
  src/main/java/seedu/address/storage/JsonAdaptedSession.java
  src/main/java/seedu/address/ui/SessionCard.java
  src/main/java/seedu/address/ui/SessionListPanel.java
Labels: bug, enhancement

#93 fixed the error message
  docs/UserGuide.md
  src/main/java/seedu/address/ui/SessionListPanel.java
Labels: bug

#94 58 earnings the past week
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/ui/EarningsBarChart.java
  src/main/java/seedu/address/ui/SessionListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SessionListPanel.fxml
Labels: enhancement, type.Story

#96 Fixed bug in hashmap for payrate tracking
  src/main/java/seedu/address/logic/commands/StudentRemoveCommand.java
  src/main/java/seedu/address/model/session/NamePayRatePair.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/storage/JsonAdaptedNamePayRatePair.java
  src/main/java/seedu/address/storage/JsonAdaptedSession.java
Labels: bug

#97 Update SessionListPanel.java
  src/main/java/seedu/address/ui/SessionListPanel.java
Labels: bug

#99 bug
  src/main/java/seedu/address/ui/SessionListPanel.java
Labels: bug
