Repository AY2223S2-CS2103T-W13-2/tp, pull requests merged in 2023-04, with the labels that each got.

#148 Branch v1.4 fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/EmptyCalendarUi.png
  docs/images/EmptySessionUi.png
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/resources/view/SessionListPanel.fxml
Labels: bug, documentation

#150 Calendar updates
  src/main/java/seedu/address/logic/CalendarLogic.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CreateSessionCommand.java
  src/main/java/seedu/address/logic/commands/EditSessionCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/calendar/CalendarEvent.java
  src/main/java/seedu/address/model/calendar/CalendarMonth.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/calendar/CalendarDisplay.java
  src/main/java/seedu/address/ui/calendar/CalendarEventListPanel.java
  src/main/java/seedu/address/ui/calendar/CalendarPopup.java
  src/main/java/seedu/address/ui/calendar/CalendarPopupContent.java
  src/main/java/seedu/address/ui/calendar/EventButton.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: bug

#151 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#152 Remove Group, Display and UniqueTagList
  src/main/java/seedu/address/logic/commands/DisplayGroupCommand.java
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/model/tag/exceptions/DuplicateTagException.java
  src/main/java/seedu/address/model/tag/exceptions/TagNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedNameBooleanPair.java
  src/main/java/seedu/address/storage/JsonAdaptedNamePayRatePair.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DisplayGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/GroupAddCommandTest.java
  src/test/java/seedu/address/logic/commands/GroupCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GroupCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/VersionedAddressBookTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/model/tag/UniqueTagListTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
Labels: bug

#154 Fix bugs
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/CreateSessionCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ShowCommandParser.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/session/UniqueSessionList.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: bug

#155 UG Fixes
  docs/UserGuide.md
  docs/images/findCarlAliceResult.png
  docs/team/tempura-person.md
Labels: documentation

#156 Standardise command messages & add Planned Enchancements
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/tempura-person.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CreateSessionCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSessionCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditSessionCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/StudentAddCommand.java
  src/main/java/seedu/address/logic/commands/StudentRemoveCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
Labels: documentation

#160 Add page breaks to User Guide.
  docs/DeveloperGuide.md
  docs/Gemfile
  docs/Gemfile.lock
  docs/UserGuide.md
  docs/team/tempura-person.md
Labels: documentation

#159 Bug fixes
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/CreateSessionCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/session/UniqueSessionList.java
Labels: bug

#158 Added PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/jengoc415.md
  docs/team/oliverloo0909.md
Labels: documentation

#161 Deleting a person deletes them from all existing sessions too
  src/main/java/seedu/address/model/AddressBook.java
Labels: bug

#163 IncomeAnalytics realtime updates
  src/main/java/seedu/address/ui/SessionListPanel.java
Labels: bug

#164 Edit PPP
  docs/team/oliverloo0909.md
Labels: documentation

#167 Branch v1.4 final fixes
  docs/index.md
  docs/team/tempura-person.md
Labels: documentation

#168 Calendar User guide
  docs/UserGuide.md
  docs/images/calendar.png
  docs/images/calendarLogic.png
  docs/images/popup.png
  src/main/java/seedu/address/ui/SessionListPanel.java
Labels: documentation

#173 Update Income Analytics
  src/main/java/seedu/address/ui/SessionListPanel.java
Labels: bug

#174 UG/DG changes
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#176 Some UG/DG changes
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#175 Calendar credits
  README.md
  docs/DeveloperGuide.md
  docs/team/tricixg.md
  src/main/java/seedu/address/logic/CalendarLogic.java
  src/main/java/seedu/address/model/calendar/CalendarMonth.java
  src/main/java/seedu/address/ui/calendar/CalendarButton.java
  src/main/java/seedu/address/ui/calendar/CalendarDisplay.java
  src/main/java/seedu/address/ui/calendar/CalendarEventListPanel.java
  src/main/java/seedu/address/ui/calendar/CalendarGrid.java
  src/main/java/seedu/address/ui/calendar/CalendarPopup.java
  src/main/java/seedu/address/ui/calendar/CalendarPopupContent.java
  src/main/java/seedu/address/ui/calendar/EventButton.java
  src/main/java/seedu/address/ui/calendar/NextButton.java
  src/main/java/seedu/address/ui/calendar/PreviousButton.java
  src/main/java/seedu/address/ui/calendar/TopCalendar.java
Labels: documentation

#177 Branch add testing
  docs/team/oliverloo0909.md
  src/main/java/seedu/address/logic/commands/DeleteSessionCommand.java
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/StudentAddCommand.java
  src/main/java/seedu/address/logic/commands/StudentRemoveCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CreateSessionCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteSessionCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/SessionBuilder.java
Labels: bug, documentation

#178 Fix sort issue
  docs/team/oliverloo0909.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: bug, documentation

#183 Update SessionListPanel
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: bug

#186 PPP fix.
  docs/team/tempura-person.md
Labels: documentation

#189 UG/DG fixes.
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation
